In [1]:
import sys
import numpy as np
#import matplotlib
#matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
pfam_id = 'PF00104'

In [3]:
ct = np.loadtxt('../../pfam_2_100k/%s_ct.txt'%pfam_id).astype(float)
di = np.loadtxt('%s/di.dat'%pfam_id).astype(float)

In [4]:
ct_thres = 8.0

In [5]:
ct1 = ct.copy()

ct_pos = ct1 < ct_thres           
ct1[ct_pos] = 1
ct1[~ct_pos] = 0

In [6]:
mask = np.triu(np.ones(di.shape[0],dtype=bool), k=5)
order = di[mask].argsort()[::-1]
ct_flat = ct1[mask][order]
print(ct_flat[0:20])

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0.]


In [7]:
mask = np.triu(np.ones(di.shape[0],dtype=bool), k=1)
order = di[mask].argsort()[::-1]
ct_flat = ct1[mask][order]
print(ct_flat[0:20])

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]


In [8]:
mask = np.triu(np.ones(di.shape[0],dtype=bool), k=2)
order = di[mask].argsort()[::-1]
ct_flat = ct1[mask][order]
print(ct_flat[0:20])

[1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0.]
